name: Build & Test
on: 
 - push 
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -y  
          sudo apt-get install -y nasm

      - name: Build via Script
        run: ./scripts/build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: nap-x86-64
          path: ./out/

  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: nap-x86-64
          path: ./out/

      - name: Run Tests via Script
        run: ./scripts/test.sh
